### ISSUE TITLE
Background color inheritance for arrows

### ISSUE THREAD

**Issue by kripod** [popperjs/popper-core#1165]
## Feature description

Currently, arrows are created [with an explicitly specified background color](https://popper.js.org/docs/v2/tutorial/#arrow) value:

```html
<div id="tooltip" role="tooltip">
  My tooltip
  <div id="arrow" data-popper-arrow></div>
</div>
```

```css
#arrow,
#arrow::before {
  position: absolute;
  width: 8px;
  height: 8px;
  z-index: -1;
}

#arrow::before {
  content: '';
  transform: rotate(45deg);
  background: #333;
}
```

However, `#arrow::before` could inherit its background color from the enclosing `#tooltip` as follows:

```diff
#arrow,
#arrow::before {
  position: absolute;
  width: 8px;
  height: 8px;
+ background: inherit;
  z-index: -1;
}

#arrow {
+ visibility: hidden;
}

#arrow::before {
+ visibility: visible;
  content: '';
  transform: rotate(45deg);
- background: #333;
}
```

## Why should this feature be part of the Popper's core?

It would allow for better composability, even as a documentation-only change.
